[package]
name = "task_feedback"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.53"
futures = "0.3.21"
serde = { version = "1.0.137", features = ["derive"], optional = true }

[dev-dependencies]
tokio = { version = "1.18.2", features = ["full"] }
